# This file created by conda-build 3.18.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 19 13:03:13 2019
# ------------------------------------------------

package:
    name: libxkbcommon
    version: 0.8.4
source:
    sha256: 299b47558188017047354995f5882d43c2c8a60367df553319dcecebadb73e1d
    url: https://github.com/xkbcommon/libxkbcommon/archive/xkbcommon-0.8.4.tar.gz
build:
    missing_dso_whitelist:
        - /lib/libc.so.6
    number: '0'
    run_exports:
        - libxkbcommon >=0.8.4,<1.0a0
    string: h516909a_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - bison 3.4 he1b5a44_0
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.6.16 hecc5488_0
        - cmake 3.14.5 hf94ab9c_0
        - curl 7.64.1 hf8cf82a_0
        - expat 2.2.5 hf484d3e_1002
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.29.1 h516909a_0
        - m4 1.4.18 h14c3975_1001
        - meson 0.51.0 py_0
        - ncurses 6.1 hf484d3e_1002
        - ninja 1.9.0 h6bb024c_0
        - openssl 1.1.1b h14c3975_1
        - pkg-config 0.29.2 h14c3975_1005
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - rhash 1.3.6 h14c3975_1001
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    host:
        - ca-certificates 2019.6.16 hecc5488_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libxcb 1.13 h14c3975_1002
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.6.7 h381d211_1004
        - readline 7.0 hf8c457e_1001
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 hed695b0_1002
        - xcb-proto 1.13 py36h14c3975_1001
        - xorg-libpthread-stubs 0.3 1
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxcb 1.12 3
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
        - xorg-xcb-proto 1.12 py36_3
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"
about:
    description: 'libxkbcommon is a keyboard keymap compiler and support library which

        processes a reduced subset of keymaps as defined by the XKB (X Keyboard

        Extension) specification.

        '
    dev_url: https://github.com/xkbcommon/libxkbcommon
    doc_url: https://xkbcommon.org/
    home: https://github.com/xkbcommon/libxkbcommon
    license: MIT/X11 Derivative
    license_family: MIT
    license_file: LICENSE
    summary: keymap handling library for toolkits and window systems
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
