# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 16 14:08:49 2019
# ------------------------------------------------

package:
    name: fribidi
    version: 1.0.5
source:
    patches:
        - meson-rpaths.patch
    sha256: 6a64f2a687f5c4f203a46fa659f43dd43d1f8b845df8d723107e8a7e6158e4ce
    url: https://github.com/fribidi/fribidi/releases/download/v1.0.5/fribidi-1.0.5.tar.bz2
build:
    number: '1002'
    run_exports:
        - fribidi >=1.0.5,<2.0a0
    string: h516909a_1002
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - meson 0.51.1 py_0
        - ncurses 6.1 hf484d3e_1002
        - ninja 1.9.0 h6bb024c_0
        - openssl 1.1.1c h516909a_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - fribidi -h
about:
    description: 'One of the missing links stopping the penetration of free software
        in Middle

        East is the lack of support for the Arabic and Hebrew alphabets. In order
        to

        have proper Arabic and Hebrew support, the bidi algorithm needs to be

        implemented. It is our hope that this library will stimulate more free

        software in the Middle Eastern countries.

        '
    dev_url: https://github.com/fribidi/fribidi
    doc_url: https://github.com/fribidi/fribidi
    home: https://github.com/fribidi/fribidi
    license: LGPL-2.1
    license_file: COPYING
    summary: The Free Implementation of the Unicode Bidirectional Algorithm.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - msarahan
