# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 15 17:45:26 2019
# ------------------------------------------------

package:
    name: pango
    version: 1.42.4
source:
    sha256: 1d2b74cd63e8bd41961f2f8d952355aa0f9be6002b52c8aa7699d9f5da597c9d
    url: http://ftp.gnome.org/pub/GNOME/sources/pango/1.42/pango-1.42.4.tar.xz
build:
    detect_binary_files_with_prefix: true
    number: '1'
    string: ha030887_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - ca-certificates 2019.6.16 hecc5488_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h14c3975_1005
        - pthread-stubs 0.4 h14c3975_1001
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - cairo 1.16.0 hfb77d84_1002
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.9.1 he983fc9_1006
        - fribidi 1.0.5 h516909a_1002
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 h6f030ca_1002
        - gobject-introspection 1.58.2 py37h5503ade_1002
        - graphite2 1.3.13 hf484d3e_1000
        - harfbuzz 2.4.0 h9f30f68_2
        - icu 64.2 he1b5a44_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 hee79883_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pcre 8.41 hf484d3e_1003
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.8 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - cairo >=1.16.0,<1.17.0a0
        - cairo >=1.16.0,<1.17.0a0
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - fribidi >=1.0.5,<2.0a0
        - harfbuzz >=2.4.0,<3.0a0
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
test:
    commands:
        - pango-view --help
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    description: 'Pango is a library for laying out and rendering of text, with an
        emphasis

        on internationalization. Pango can be used anywhere that text layout is

        needed, though most of the work on Pango so far has been done in the

        context of the GTK+ widget toolkit. Pango forms the core of text and font

        handling for GTK+-2.x.

        '
    dev_url: https://gitlab.gnome.org/GNOME/pango
    doc_url: http://www.pango.org/
    home: http://www.pango.org/
    license: LGPL-2.1
    license_file: COPYING
    summary: Text layout and rendering engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
        - pkgw
