# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 31 00:01:22 2019
# ------------------------------------------------

package:
    name: nss
    version: '3.46'
source:
    fn: nss-3.46.tgz
    patches:
        - nss-3.39-standalone-1.patch
    sha256: 6b699649d285602ba258a4b0957cb841eafc94eff5735a9da8da0adbb9a10cef
    url: https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_46_RTM/src/nss-3.46.tar.gz
build:
    number: '0'
    string: he751ad9_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526h14c3975_9
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - cmake 3.15.2 hf94ab9c_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.31.0 h516909a_0
        - m4 1.4.18 h14c3975_1001
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h14c3975_1005
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - nspr 4.20 hf484d3e_1000
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_1
        - zlib 1.2.11 h516909a_1005
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - nspr >=4.20,<5.0a0
        - sqlite >=3.29.0,<4.0a0
        - sqlite >=3.29.0,<4.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libsoftokn3${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libsoftokn3.chk
        - test -f ${PREFIX}/lib/libnss3${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libsmime3${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libssl3${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libnssckbi${SHLIB_EXT}
about:
    description: 'Network Security Services (NSS) is a set of libraries designed to
        support

        cross-platform development of security-enabled client and server

        applications. Applications built with NSS can support SSL v3, TLS,

        PKCS #5, PKCS #7, PKCS #11, PKCS #12, S/MIME, X.509 v3 certificates,

        and other security standards.

        '
    dev_url: https://hg.mozilla.org/projects/nss
    doc_url: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
    home: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
    license: MPL 2
    license_file: nss/COPYING
    summary: A set of libraries designed to support cross-platform development of
        security-enabled client and server applications.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - marcelotrevisani
