# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug  8 12:41:22 2019
# ------------------------------------------------

package:
    name: ipykernel
    version: 5.1.2
source:
    sha256: b503913e0b4cce7ed2de965457dfb2edd633e8234161a60e23f2fe2161345d12
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-5.1.2.tar.gz
build:
    number: '0'
    script:
        - /home/conda/feedstock_root/build_artifacts/ipykernel_1565268170526/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
            setup.py bdist_wheel
        - cd dist
        - /home/conda/feedstock_root/build_artifacts/ipykernel_1565268170526/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
            -m pip install ipykernel-5.1.2-py3-none-any.whl --no-deps -vv
        - /home/conda/feedstock_root/build_artifacts/ipykernel_1565268170526/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
            -m ipykernel install --sys-prefix
    string: py37h5ca1d4c_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - backcall 0.1.0 py_0
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py37_1
        - decorator 4.4.0 py_0
        - ipython 7.7.0 py37h5ca1d4c_0
        - ipython_genutils 0.2.0 py_1
        - jedi 0.14.1 py37_0
        - jupyter_client 5.3.1 py_0
        - jupyter_core 4.4.0 py_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libsodium 1.0.17 h516909a_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - parso 0.5.1 py_0
        - pexpect 4.7.0 py37_0
        - pickleshare 0.7.5 py37_1000
        - pip 19.2.1 py37_0
        - prompt_toolkit 2.0.9 py_0
        - ptyprocess 0.6.0 py_1001
        - pygments 2.4.2 py_0
        - python 3.7.3 h33d41f4_1
        - python-dateutil 2.8.0 py_0
        - pyzmq 18.0.2 py37h1768529_2
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py37_0
        - six 1.12.0 py37_1000
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - tornado 6.0.3 py37h516909a_0
        - traitlets 4.3.2 py37_1000
        - wcwidth 0.1.7 py_1
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h14c3975_1001
        - zeromq 4.3.2 he1b5a44_2
        - zlib 1.2.11 h516909a_1005
    run:
        - ipython >=5.0
        - jupyter_client
        - python >=3.7,<3.8.0a0
        - tornado >=4.2
        - traitlets >=4.1
test:
    commands:
        - jupyter kernelspec list
        - pytest --pyargs ipykernel
    imports:
        - ipykernel
    requires:
        - curio
        - ipython
        - nose
        - numpy
        - pytest
about:
    description: 'A powerful interactive Python shell and a Jupyter kernel to work
        with

        Python code in Jupyter notebooks and other interactive frontends.

        '
    dev_url: https://github.com/ipython/ipykernel
    doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
