# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 27 09:47:57 2019
# ------------------------------------------------

package:
    name: nbconvert
    version: 5.6.0
source:
    sha256: 427a468ec26e7d68a529b95f578d5cbf018cb4c1f889e897681c2b6d11897695
    url: https://pypi.io/packages/source/n/nbconvert/nbconvert-5.6.0.tar.gz
build:
    entry_points:
        - jupyter-nbconvert = nbconvert.nbconvertapp:main
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/nbconvert_1566899363325/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py37_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.2.3 py37_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - setuptools 41.2.0 py37_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - bleach
        - defusedxml
        - entrypoints >=0.2.2
        - jinja2
        - jupyter_core
        - mistune >=0.8.1
        - nbformat >=4.4
        - pandoc >=1.12.1
        - pandocfilters >=1.4.1
        - pygments
        - python >=3.7,<3.8.0a0
        - testpath
        - traitlets >=4.2
test:
    commands:
        - jupyter nbconvert --help
        - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb
    imports:
        - nbconvert
        - nbconvert.exporters
        - nbconvert.filters
        - nbconvert.postprocessors
        - nbconvert.preprocessors
        - nbconvert.resources
        - nbconvert.tests
        - nbconvert.utils
        - nbconvert.writers
    source_files:
        - nbconvert/tests/files/notebook1.ipynb
about:
    description: 'The nbconvert tool, jupyter nbconvert, converts notebooks to various
        other

        formats via Jinja templates. The nbconvert tool allows you to convert an

        .ipynb notebook file into various static formats.

        '
    dev_url: https://github.com/jupyter/nbconvert
    doc_url: http://nbconvert.readthedocs.org/
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Converting Jupyter Notebooks
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - jakirkham
        - minrk
        - mpacer
        - mseal
        - ocefpaf
        - pelson
        - takluyver
