# This file created by conda-build 3.18.9
# ------------------------------------------------

package:
    name: libllvm8
    version: 8.0.1
source:
    patches:
        - 0001-Revert-Limit-size-of-non-GlobalValue-name.patch
        - D47188-svml-VF.patch
    sha256: 44787a6d02f7140f145e2250d56c9f849334e11f9ae379827510ed72f12b75e7
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/llvm-8.0.1.src.tar.xz
build:
    activate_in_script: true
    number: 0
    run_exports:
        - libllvm8 8.0.1 0
    string: hc9558a2_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - cmake 3.15.1 hf94ab9c_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.30.1 h516909a_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - rhash 1.3.6 h14c3975_1001
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -f $PREFIX/lib/libLLVM-8${SHLIB_EXT}
about:
    dev_url: https://github.com/llvm-mirror/llvm
    home: http://llvm.org/
    license: NCSA
    license_file: LICENSE.TXT
    summary: Development headers and libraries for LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - inducer
        - isuruf
        - jakirkham
        - mattwala
        - mingwandroid
        - pitrou
