# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 27 20:06:18 2019
# ------------------------------------------------

package:
    name: pyrsistent
    version: 0.15.4
source:
    sha256: 34b47fa169d6006b32e99d4b3c4031f155e6e68ebcc107d6454852e8e0ee6533
    url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-0.15.4.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/pyrsistent_1564258067408/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed -vvv
    string: py37h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - atomicwrites 1.3.0 py_0
        - attrs 19.1.0 py_0
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py37_1
        - importlib_metadata 0.18 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - more-itertools 7.1.0 py_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - packaging 19.0 py_0
        - pip 19.2.1 py37_0
        - pluggy 0.12.0 py_0
        - py 1.8.0 py_0
        - pyparsing 2.4.1.1 py_0
        - pytest 5.0.1 py37_1
        - pytest-runner 5.1 py_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py37_0
        - six 1.12.0 py37_1000
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wcwidth 0.1.7 py_1
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h14c3975_1001
        - zipp 0.5.1 py_0
        - zlib 1.2.11 h516909a_1005
    run:
        - libgcc-ng >=7.3.0
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - pyrsistent
    requires:
        - hypothesis
        - pytest
about:
    home: http://github.com/tobgu/pyrsistent/
    license: MIT
    license_family: MIT
    license_file: LICENCE.mit
    summary: Persistent/Functional/Immutable data structures
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
