# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 28 19:36:09 2019
# ------------------------------------------------

package:
    name: terminado
    version: 0.8.2
source:
    sha256: de08e141f83c3a0798b050ecb097ab6259c3f0331b2f7b7750c9075ced2c20c2
    url: https://pypi.io/packages/source/t/terminado/terminado-0.8.2.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/terminado_1553801917355/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        setup.py install
    string: py37_0
requirements:
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1001
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - ptyprocess
        - python >=3.7,<3.8.0a0
        - tornado >=4
test:
    commands:
        - nosetests terminado
    imports:
        - terminado
    requires:
        - nose
about:
    description: 'Terminado is a Tornado websocket backend for the term.js Javascript

        terminal emulator library.

        '
    dev_url: https://github.com/takluyver/terminado
    doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
    doc_url: http://terminado.readthedocs.org/en/latest/
    home: https://github.com/jupyter/terminado
    license: BSD-2-Clause
    license_file: LICENSE
    summary: Terminals served by tornado websockets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - ocefpaf
        - pelson
        - takluyver
