# This file created by conda-build 3.18.9
# ------------------------------------------------

package:
    name: libclang
    version: 8.0.1
source:
    patches:
        - patches/0001-Find-conda-gcc-installation.patch
        - patches/0001-Set-VERSION-in-osx-as-well.patch
        - patches/0002-Fix-sysroot-detection-for-linux.patch
        - patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
        - patches/0003-clang-Fix-normalizeProgramName-s-handling-of-dots-ou.patch
    sha256: 70effd69f7a8ab249f66b0a68aba8b08af52aa2ab710dfb8a0fba102685b1646
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/cfe-8.0.1.src.tar.xz
build:
    noarch: false
    number: '0'
    script: install_libclang.sh
    string: hc9558a2_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - cmake 3.15.1 hf94ab9c_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.30.1 h516909a_0
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libllvm8 8.0.1 hc9558a2_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - llvm 8.0.1 0
        - llvm-tools 8.0.1 hc9558a2_0
        - llvmdev 8.0.1 hc9558a2_0
    run:
        - libgcc-ng >=7.3.0
        - libllvm8 8.0.1 hc9558a2_0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -f "$PREFIX/lib/libclang.so"
        - test -f "$PREFIX/lib/libclang.so.8"
about:
    home: http://llvm.org/
    license: NCSA
    license_file: LICENSE.TXT
    summary: Development headers and libraries for Clang
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - inducer
        - isuruf
        - jakirkham
        - mattwala
