# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 25 13:05:23 2019
# ------------------------------------------------

package:
    name: pip
    version: 19.2.3
source:
    sha256: e7a31f147974362e6c82d84b91c7f2bdf57e4d3163d3d454e6c3e71944d67135
    url: https://pypi.io/packages/source/p/pip/pip-19.2.3.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal:main
    number: '0'
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py37_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - setuptools 41.2.0 py37_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
