# This file created by conda-build 3.18.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun 21 15:52:41 2019
# ------------------------------------------------

package:
    name: prometheus_client
    version: 0.7.1
source:
    sha256: 6bfe4192c03f81c36c86a2dd7cd1fa151e470cd3d9fd24fe15e63abb85383aa0
    url: https://github.com/prometheus/client_python/archive/v0.7.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/prometheus_client_1561132487947/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.1.1 py27_0
        - python 2.7.15 h721da81_1008
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.1 py27_0
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - python
test:
    imports:
        - prometheus_client
        - prometheus_client.bridge
about:
    home: https://github.com/prometheus/client_python
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Python client for the Prometheus monitoring system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jessicaaustin
        - kwilcox
        - ocefpaf
