# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jul 18 13:57:30 2019
# ------------------------------------------------

package:
    name: pyzmq
    version: 18.0.2
source:
    sha256: 31a11d37ac73107363b47e14c94547dbfc6a550029c3fe0530be443199026fc2
    url: https://pypi.io/packages/source/p/pyzmq/pyzmq-18.0.2.tar.gz
build:
    number: '2'
    string: py37h1768529_2
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py37_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libsodium 1.0.17 h516909a_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.1.1 py37_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py37_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h14c3975_1001
        - zeromq 4.3.2 he1b5a44_2
        - zlib 1.2.11 h516909a_1005
    run:
        - libgcc-ng >=7.3.0
        - libsodium >=1.0.17,<1.0.18.0a0
        - libsodium >=1.0.17,<1.0.18.0a0
        - libstdcxx-ng >=7.3.0
        - python >=3.7,<3.8.0a0
        - zeromq >=4.3.2,<4.4.0a0
        - zeromq >=4.3.2,<4.4.0a0
test:
    commands:
        - py.test --pyargs zmq.tests.test_socket
    imports:
        - zmq
        - zmq.backend.cython.socket
        - zmq.backend.cython.utils
        - zmq.devices.monitoredqueue
    requires:
        - pytest
about:
    home: https://github.com/zeromq/pyzmq
    license: BSD 3-clause
    license_file: COPYING.BSD
    summary: Python bindings for zeromq
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - jakirkham
        - minrk
        - msarahan
        - ocefpaf
        - pelson
